- name: Deploy on docker containers
  hosts: webserver
  become: true
  become_user: root
  tasks:
  - name: Install git and docker
    package: name={{item}} state=present
    loop:
    - git
    - docker
    - tree
    - wget
  - name: Start docker service
    service: name=docker state=started
  - name: clone the github repo
    git:
     repo=https://github.com/Saad4509/myansible.git
     dest=/temp/myrepo
  - name: switch to the directory and build docker image
    command: chdir=/temp/myrepo docker build -t mydockerimage
  - name: Run the image to deploy app on container
    command: docker run -d -P mydockerimage
