---
- hosts: webservers
  become: true
  become_user: root
  tasks:
    - name: Install necessary packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - tomcat
        - docker
        - git

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Clone the repository
      git:
        repo: https://github.com/Saad4509/myansible.git
        dest: /tmp/mygitrepo2

    - name: Build Docker image locally
      command: chdir=/tmp/mygitrepo2/ docker build -t myadd:ansible2
      register: docker_build
      ignore_errors: true

    - name: Check if Docker build succeeded
      fail:
        msg: "Docker build failed"
      when: docker_build.failed

    - name: Create container
      command: docker run -itd -P myadd:ansible2 .
      ignore_errors: true
